### ISSUE TITLE
Duplicate response with rut contain dots

### ISSUE THREAD

**Issue by joiseimagemaker** [ccuetoh/libreapi#4]
When send a request using a RUT with format xx.xxx.xxx-x return duplicate json of type string.

example with dots: https://api.libreapi.cl/rut/activities?rut=17.758.605-6
![image](https://user-images.githubusercontent.com/89589526/197894406-705a09e6-6c8f-4aee-9e52-697e836ed38c.png)

example without dots: https://api.libreapi.cl/rut/activities?rut=17758605-6
![image](https://user-images.githubusercontent.com/89589526/197894462-d1598343-f25c-4856-a950-64c18f341aaa.png)

**Comment by ccuetoh** [comment]
Hi and thanks for letting me know! 

The issue is caused by the caching middleware handling the requests in a non-thread-safe way ([#15](https://github.com/gin-contrib/cache/issues/15)). 

https://github.com/ccuetoh/libreapi/blob/275471019f7dfbcaf6140efaa11829765cbcaa08/pkg/api.go#L100

The immediate solution would be to change the cache handler calls from CachePage to CachePageAtomic introduced in [PR #21]( https://github.com/gin-contrib/cache/pull/21), but since the issue occurs rarely, and branch [v2](/ccuetoh/libreapi/tree/v2) swaps out the caching library for another one, I'll just wait for the merge. In the mean time I flushed the cache so the issue is resolved for the RUT given above. 

I'll keep the issue open until v2 is merged, which should go live during this week.

**Comment by joiseimagemaker** [comment]
Thanks you!, it is working now
